import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ResponsiveAppBar from "./Components/Topbar"

import { AppBar, Toolbar, Button, Box, Typography, Grid, Paper, Container } from '@mui/material';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ResponsiveAppBar></ResponsiveAppBar>
        {children}
        <Box sx={{ backgroundColor: '#333', color: 'white', padding: 3, textAlign: 'center' }}>
        <Typography variant="body2">&copy; 2024 My Website. All rights reserved.</Typography>
        <Typography variant="body2" sx={{ marginTop: 1 }}>
          Follow us on social media!
        </Typography>
      </Box>

      </body>
    </html>
  );
}
